[workspace]
members = [
    "bulletproofs",
    "relations",
]

resolver = "2"

[patch.crates-io]
#dock_crypto_utils = { path = "../crypto/utils" }
#schnorr_pok = { path = "../crypto/schnorr_pok" }
dock_crypto_utils = { git = "https://github.com/PolymeshAssociation/crypto" }
schnorr_pok = { git = "https://github.com/PolymeshAssociation/crypto" }

[workspace.dependencies]
dock_crypto_utils = { version = "0.22.0", default-features = false }
schnorr_pok = { version = "0.22.0", default-features = false }

[profile.release]
lto = true
