[workspace]
members = [
    "bulletproofs",
    "relations",
    "ark-ec-divisors",
    "ark-dlog-gadget"
]

resolver = "2"

[patch.crates-io]
#dock_crypto_utils = { path = "../crypto/utils" }
dock_crypto_utils = { git = "https://github.com/PolymeshAssociation/crypto", branch = "main" }

## Polymesh changes.
#ark-serialize = { path = "../arkworks-algebra/serialize" }
#ark-ec = { path = "../arkworks-algebra/ec" }
#ark-host-msm = { path = "../arkworks-algebra/host-msm" }
#ark-ff = { path = "../arkworks-algebra/ff" }
#ark-poly = { path = "../arkworks-algebra/poly" }
#ark-pallas = { path = "../arkworks-algebra/curves/pallas" }
#ark-vesta = { path = "../arkworks-algebra/curves/vesta" }
#ark-secp256k1 = { path = "../arkworks-algebra/curves/secp256k1" }
#ark-secq256k1 = { path = "../arkworks-algebra/curves/secq256k1" }
#ark-helios = { path = "../arkworks-algebra/curves/helios" }
#ark-selene = { path = "../arkworks-algebra/curves/selene" }
#ark-ed25519 = { path = "../arkworks-algebra/curves/ed25519" }
#ark-curve25519 = { path = "../arkworks-algebra/curves/curve25519" }
#ark-wei25519 = { path = "../arkworks-algebra/curves/wei25519" }

ark-serialize = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ec = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-host-msm = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ff = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-poly = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-pallas = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-vesta = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-secp256k1 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-secq256k1 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-helios = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-selene = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ed25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-curve25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-wei25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }


[workspace.dependencies]
dock_crypto_utils = { version = "0.22.0", default-features = false }
ark-ff = { version = "0.5.0", default-features = false }
ark-ec = { version = "0.5.0", default-features = false }
ark-host-msm = { version = "0.5.0", default-features = false }
ark-serialize = { version = "0.5.0", default-features = false }
ark-std = { version = "0.5.0", default-features = false }
ark-poly = { version = "0.5.0", default-features = false }
ark-pallas = { version = "0.5.0", default-features = false, features = ["curve"] }
ark-vesta = { version = "0.5.0", default-features = false }
ark-secp256k1 = { version = "0.5.0", default-features = false }
ark-secq256k1 = { version = "0.5.0", default-features = false }
ark-helios = { version = "0.5.0", default-features = false }
ark-selene = { version = "0.5.0", default-features = false }
ark-ed25519 = { version = "0.5.0", default-features = false }
ark-curve25519 = { version = "0.5.0", default-features = false }
ark-wei25519 = { version = "0.5.0", default-features = false }

[profile.release]
opt-level = 3
lto = true

[profile.bench]
inherits = "release"
# https://doc.rust-lang.org/rustc/linker-plugin-lto.html
lto = "fat"

# Use this profile to compile binary for deployment
[profile.production]
inherits = "release"
# Keeping lto independent from bench for now
# https://doc.rust-lang.org/rustc/linker-plugin-lto.html
lto = "fat"
# https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units
codegen-units = 1
