[package]
name = "ark-dlog-gadget"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-serialize = { workspace = true, default-features = false }
ark-ec = { workspace = true, default-features = false }
ark-ff = { workspace = true, default-features = false }
dock_crypto_utils = { workspace = true, default-features = false }
rayon = {version = "1.5.3", default-features = false, optional = true }
zeroize.workspace = true
rand_core = { version = "0.6", default-features = false }
rand = { version = "0.8", default-features = false, optional = true }
subtle = { version = "2", default-features = false }
ark-std = { version = "0.5.0", default-features = false }
ark-ed25519 = { version = "0.5.0", default-features = false, optional = true }
ark-pallas = { workspace = true, default-features = false, optional = true }
ark-vesta = { workspace = true, default-features = false, optional = true }
ark-helios = { workspace = true, default-features = false, optional = true }
ark-selene = { workspace = true, default-features = false, optional = true }
ark-wei25519 = { workspace = true, optional = true }
ark-curve25519 = { workspace = true, optional = true }
generic-array = { version = "1", default-features = false, features = ["alloc", "zeroize"] }
bulletproofs = {path = "../bulletproofs", default-features = false}
ark-ec-divisors = {path = "../ark-ec-divisors", default-features = false}
thiserror = { version = "2", default-features = false }

[dev-dependencies]
ark-pallas = { workspace = true }
ark-vesta = { workspace = true }
ark-helios = { workspace = true }
ark-selene = { workspace = true }
ark-wei25519 = { workspace = true }
ark-curve25519 = { workspace = true }
ark-secp256k1 = { workspace = true }
ark-secq256k1 = { workspace = true }
ark-ec-divisors = {path = "../ark-ec-divisors", features = ["default", "helios", "selene", "wei25519", "secp256k1", "secq256k1"]}
criterion = "0.8"

[[bench]]
name = "dlog"
harness = false


[features]
default = [
    "std", "asm",
    "pallas", "vesta",
    "rand", "parallel"
]

no_std = []
std = [
    "ark-ec/std",
    "ark-ff/std",
    "ark-serialize/std",
    "ark-std/std",
    "dock_crypto_utils/std",
    "subtle/std",
    "ark-ec-divisors/std",
    "bulletproofs/std",
    "thiserror/std"
]
asm = ["ark-ff/asm", "ark-pallas/asm", "ark-vesta/asm", "ark-helios/asm", "ark-selene/asm"]
parallel = [
    "std",
    "rayon",
    "dock_crypto_utils/parallel",
    "ark-ec-divisors/parallel"
]
parallel_full = [
    "parallel",
    "ark-ff/parallel",
    "ark-ec/parallel",
    "dock_crypto_utils/parallel_full",
    "ark-ec-divisors/parallel_full"
]
ed25519 = ["ark-ed25519"]
pallas = ["ark-pallas", "ark-ec-divisors/pallas"]
vesta = ["ark-vesta", "ark-ec-divisors/vesta"]
helios = ["ark-helios", "ark-ec-divisors/helios"]
selene = ["ark-selene", "ark-ec-divisors/selene"]
wei25519 = ["ark-wei25519", "ark-curve25519", "ark-ec-divisors/wei25519"]