[package]
name = "bulletproofs"
version = "2.0.0"
authors = ["Cathie Yun <cathieyun@gmail.com>", 
           "Henry de Valence <hdevalence@hdevalence.ca>",
           "Oleg Andreev <oleganza@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/dalek-cryptography/bulletproofs"
categories = ["cryptography"]
keywords = ["cryptography", "crypto", "ristretto", "zero-knowledge", "bulletproofs"]
description = "A pure-Rust implementation of Bulletproofs using Ristretto"
edition = "2018"

[dependencies]
sha3 = { version = "0.9.1", default-features = false }
digest = { version = "0.9.0", default-features = false }
rand = { version = "0.8", default-features = false, optional = true }
rand_core = { version = "0.6", default-features = false }
log = { version = "0.4.27", default-features = false }
byteorder = { version = "1", default-features = false }
thiserror = { version = "2", default-features = false }
ark-ff = { workspace = true, default-features = false }
ark-ec = { workspace = true, default-features = false }
ark-serialize = { workspace = true, default-features = false }
ark-std = { workspace = true, default-features = false }
rayon = {version = "1.5.3", default-features = false, optional = true }
zeroize = { version = "1", features = ["zeroize_derive"] }
dock_crypto_utils = { workspace = true, default-features = false }
sha2 = { version = "0.10.8", default-features = false }
ark-pallas = { workspace = true, default-features = false, features = ["curve"] }
ark-vesta = { workspace = true, default-features = false }
ark-helios = { workspace = true, default-features = false }
ark-selene = { workspace = true, default-features = false }
ark-wei25519 = { workspace = true, default-features = false }
hashbrown = { version = "0.15.0", default-features = false }

polkavm-derive = { version = "0.32.0", optional = true }
ark-host-msm = { workspace = true, default-features = false, optional = true }
lazy_static = { version = "1.5.0", default-features = false, optional = true }

[target.'cfg(all(target_has_atomic = "8", target_has_atomic = "16", target_has_atomic = "32", target_has_atomic = "64", target_has_atomic = "ptr"))'.dependencies]
ahash = { version = "0.8", default-features = false }

[target.'cfg(not(all(target_has_atomic = "8", target_has_atomic = "16", target_has_atomic = "32", target_has_atomic = "64", target_has_atomic = "ptr")))'.dependencies]
fnv = { version = "1.0", default-features = false }

[dev-dependencies]
test-log = "0.2"
criterion = "0.7"

[features]
default = ["std", "parallel", "asm", "host_hash_to_curve"]

no_std = []
std = ["rand/std", "thiserror/std", "sha2/std", "ark-pallas/std", "ark-vesta/std", "dock_crypto_utils/std", "ahash/std", "impl_host_hash_to_curve", "lazy_static"]
asm = ["ark-ff/asm", "sha2/asm"]
parallel = ["std", "rayon" ]
parallel_full = [ "parallel", "dock_crypto_utils/parallel_full" ]

# Enable host `hash_to_curve` support.
host_hash_to_curve = [
    "ark-host-msm",
]
# For the host-side.
impl_host_hash_to_curve = [
    "ark-host-msm",
]
polkavm = [
    "host_hash_to_curve",
    "polkavm-derive",
]

[[test]]
name = "r1cs"

[[bench]]
name = "generators"
harness = false

[[bench]]
name = "r1cs"
harness = false
