[package]
name = "relations"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = { version = "0.10.6", default-features = false }
rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
log = { version = "0.4.27", default-features = false }
thiserror = { version = "2", default-features = false }
bulletproofs = { path = "../bulletproofs", default-features = false }
ark-ff = { workspace = true, default-features = false }
ark-ec = { workspace = true, default-features = false }
ark-serialize = { workspace = true, default-features = false }
ark-std = { workspace = true, default-features = false }
ark-crypto-primitives = { version = "0.5.0", default-features = false, features = ["signature"] }
digest = { version = "0.10.7", default-features = false }
blake2 = { version = "0.10", default-features = false }
rayon = { version = "1.5.3", optional = true, default-features = false }
ark-pallas = { workspace = true, default-features = false, features = ["curve"] }
ark-vesta = { workspace = true, default-features = false }
ark-helios = { workspace = true, default-features = false }
ark-selene = { workspace = true, default-features = false }
dock_crypto_utils = { workspace = true, default-features = false }
zeroize = { version = "1", features = ["zeroize_derive"] }
ark-ec-divisors = { path = "../ark-ec-divisors", default-features = false, features = ["pallas", "vesta", "helios", "selene", "wei25519"] }
ark-dlog-gadget = { path = "../ark-dlog-gadget", default-features = false, features = ["pallas", "vesta", "helios", "selene", "wei25519"] }

[dev-dependencies]
test-log = "0.2"
criterion = "0.7"
ark-secp256k1.workspace = true
ark-secq256k1.workspace = true
lazy_static = "1.5.0"
ark-dlog-gadget = {path = "../ark-dlog-gadget", features = ["default", "helios", "selene", "wei25519"]}
ark-ec-divisors = {path = "../ark-ec-divisors", features = ["default", "helios", "selene", "wei25519"]}


[features]
default = ["asm", "std", "parallel"]

no_std = []
std = ["rand/std", "thiserror/std", "bulletproofs/std", "ark-serialize/std", "dock_crypto_utils/std", "ark-ec-divisors/std", "ark-dlog-gadget/std"]

asm = ["ark-ff/asm", "bulletproofs/asm"]
parallel = ["std", "rayon" ]
parallel_full = [ "parallel", "bulletproofs/parallel_full", "dock_crypto_utils/parallel_full", "ark-ec-divisors/parallel_full", "ark-dlog-gadget/parallel_full" ]
bench_prover = []
detailed_benchmarks = []
usenix = ["bench_prover"]
table1 = ["usenix"]
table2 = ["usenix"]
table3 = ["usenix"]
all-tables = ["table1", "table2", "table3"]

#[[bench]]
#name = "batched_select_rerandomize"
#harness = false

[[bench]]
name = "select_rerandomize"
harness = false

#[[bench]]
#name = "coin"
#harness = false

[[bench]]
name = "accumulator"
harness = false

[[bench]]
name = "range_proof"
harness = false

[[bench]]
name = "curve_tree"
harness = false

[[bench]]
name = "curve_tree_new"
harness = false

[[bench]]
name = "select"
harness = false

[[bench]]
name = "batched_curve_tree"
harness = false

[[bench]]
name = "batched_curve_tree_new"
harness = false

# TODO: Uncomment
#[build]
# Adds architecture specific optimizations including those enabling the asm backend for ark_ff. It could potentially cause slowdowns from other features.
#rustflags = "-C target-cpu=native"
# You could alternatively add support for the asm backend through "-C target-feature=+bmi2,+adx", but the binary would only run on systems supporting these instructions.
